name: C/C++ CI_UBUNTU

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v1
      - name: sub
        run: git submodule update --init --recursive
      - name: make
        run: make
